apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: bashofmann/rancher-demo:1.1.0
          ports:
            - containerPort: 8080
          env:
            - name: TITLE
              value: "App 1"
            - name: CONTAINER_COLOR
              value: purple
