kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app1

spec:

  rules:
    - http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: app1
                port:
                  number: 80
