apiVersion: v1
kind: Secret
metadata:
  name: gitlab-https-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.pissenlit.com/root/kube-conf-beroux.git
  project: default
  insecure: "true"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://gitlab.pissenlit.com/root/kube-conf-beroux.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
